[build]
  publish = "."
  command = "echo 'No build step required'"

[dev]
  command = "netlify dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
